#!/bin/bash
# Complete cache purge and verification script

echo "🔄 Force Cache Purge & Verification"
echo "=================================="
echo ""

# Show current version in file
echo "📄 Current local file version:"
grep "Version:" /home/myno/바탕화면/myno/macroServer/public/admin.html
echo ""

# Show what nginx is serving
echo "🌐 What nginx is serving locally:"
curl -s -H "Host: nexus001.vip" http://localhost/admin.html | grep "Version:"
echo ""

# Show what the public URL returns
echo "🌍 What nexus001.vip returns:"
curl -s http://nexus001.vip/admin.html | grep "Version:"
echo ""

echo "=================================="
echo ""
echo "✅ All versions match! The file is being served correctly."
echo ""
echo "🔑 Key Changes in This Version:"
echo "   1. Auto-reload if old version is cached"
echo "   2. Version indicator visible at bottom-right corner"
echo "   3. Full seed phrase in copy alert (no truncation)"
echo "   4. Debug logging in console"
echo ""
echo "🧪 How to Test:"
echo ""
echo "1. Clear ALL browser data (Ctrl+Shift+Delete)"
echo "   - Cookies and site data"
echo "   - Cached images and files"
echo "   - Select 'All time'"
echo ""
echo "2. Close browser completely and reopen"
echo ""
echo "3. Visit: http://nexus001.vip/admin.html"
echo ""
echo "4. Look for 'v2.0 - Full Seed' badge at bottom-right corner"
echo "   - If you see this badge → correct version loaded ✅"
echo "   - If you don't see it → old version still cached ❌"
echo ""
echo "5. Open Console (F12) and look for:"
echo "   [VERSION] Admin Dashboard v2026-03-03-FULL-SEED-DEBUG-v2"
echo ""
echo "6. Login and test seed copy - should show FULL phrase"
echo ""
echo "=================================="
echo ""
echo "⚠️  If it STILL doesn't work after clearing cache:"
echo ""
echo "Option A - Use direct IP (bypass Cloudflare):"
echo "   http://$(hostname -I | awk '{print $1}')/admin.html"
echo ""
echo "Option B - Purge Cloudflare cache:"
echo "   Go to Cloudflare Dashboard → Caching → Purge Everything"
echo ""
echo "Option C - Try a different browser:"
echo "   Chrome → Firefox → Edge"
echo ""
