/** @type {readonly string[]} KIS 해외선물옵션 실시간체결가 HDFFF020 컬럼 순서 (공식 샘플 기준) */
export const HDFFF020_COLUMNS = Object.freeze([
  'series_cd',
  'bsns_date',
  'mrkt_open_date',
  'mrkt_open_time',
  'mrkt_close_date',
  'mrkt_close_time',
  'prev_price',
  'recv_date',
  'recv_time',
  'active_flag',
  'last_price',
  'last_qntt',
  'prev_diff_price',
  'prev_diff_rate',
  'open_price',
  'high_price',
  'low_price',
  'vol',
  'prev_sign',
  'quotsign',
  'recv_time2',
  'psttl_price',
  'psttl_sign',
  'psttl_diff_price',
  'psttl_diff_rate',
]);

